site_name: Zona de documents
site_url: https://calaix.github.io/mkdocs/

# Enllaç al repositori del teu projecte
repo_url: https://github.com/calaix/mkdocs
repo_name: calaix/mkdocs
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  language: ca
  logo: images/logo.png
  favicon: images/favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - navigation.footer
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - tables

nav:
  - Inici: index.md
  - Proves:
      - proves/index.md
      - proves/1.md
      - proves/2.md
      - proves/3.md
      - proves/4.md
  - Mkdocs:
      - mkdocs/index.md
      - mkdocs/1.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com
      name: GitHub
    - icon: fontawesome/brands/docker
      link: https://www.docker.com/
      name: docker
    - icon: fontawesome/brands/mastodon
      link: https://joinmastodon.org/es
      name: Mastodon
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/?lang=es
      name: x-twitter

extra_css:
  - https://cdn.jsdelivr.net/npm/abcjs@6.2.2/abcjs-audio.css
  - stylesheets/custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/abcjs@6.2.2/dist/abcjs-basic-min.js
  - javascripts/abc-render.js
